FROM golang:{{.GoVersion}}-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /myapp

FROM alpine:latest
# или gcr.io/distroless/static-debian12 для ультра-мини
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /myapp .
EXPOSE {{.Port}}
CMD ["./myapp"]